from setuptools import setup

setup(
    name='my_tipyverse',
    version='0.1',
    description='A package to install Python equivalents of R Tidyverse packages',
    author='Sebastian Dunn',
    author_email='sebastiancdunn@gmail.com',
    packages=['my_tidyverse'],
    install_requires=[
        'lets-plot',
        'siuba',
        'swifter',
        'sqlalchemy',
        'mysql-connector-python',
        'pyreadstat',
        'requests',
        'google-api-python-client',
        'google-auth-httplib2',
        'google-auth-oauthlib',
        'pydrive2',
        'beautifulsoup4',
        'lxml',
        'playwright',
        'toolz',
        'polars',
        'fastapi',
        'dask',
        'plotnine',
        'seaborn',
        'numpy',
        'scipy',
        'statsmodels',
        'altair'
    ],
    extras_require={
        'notebook': ['swifter'],
        'groupby': ['swifter'],
    },
    python_requires='>=3.6',
)